language: cpp
compiler:
    - clang
before_install:
    - sudo apt-add-repository -y ppa:boost-latest/ppa
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq libboost1.55-all-dev autoconf automake autoconf-archive
script:
    - autoreconf;automake --add-missing;autoreconf
    - ./configure --with-boost-libdir=/usr/lib/x86_64-linux-gnu
    - make -j8 CXX=clang++ check
